version: 2.1
orbs:
  node: circleci/node@5.1.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - run: " ls && node index.js" 
workflows:
  example-workflow:
    jobs:
      - example-job
